### ISSUE TITLE
error if password is null or undefined

### ISSUE THREAD

**Issue by jamesdixon** [bsiddiqui/bookshelf-bcrypt#6]
If a password is passed as `null` or `undefined`, an error is thrown. Will submit a PR.

**Comment by alanhoff** [comment]
What would be the expected behaviour for an empty password?

**Comment by jamesdixon** [comment]
@alanhoff I would expect nothing to happen since a `null` or `undefined` value cannot be hashed. 

I came across this particular issue due to the fact that when I create new user accounts, I do not set a password. Instead, an email is sent and the user creates their own password and the account is then activated.

I don't believe that the plugin should be responsible for any sort of validation. In my opinion, that lies outside of the scope of the plugin. You could argue that the plugin should throw an error if a `null` or `undefined` value was passed. With that said, maybe it might be more desirable to throw an error by default and allow for a setting to override this behavior. Thoughts?

**Comment by bsiddiqui** [comment]
I'd be more in favor of us throwing an error with the option to allow an empty password - that way the plugin protects the standard case and is still flexible enough for your use case.

**Comment by alanhoff** [comment]
@bsiddiqui I agree. @jamesdixon let me know if you need help with the PR

**Comment by jamesdixon** [comment]
Sounds good! I'll do my best to get this updated soon.

**Comment by jamesdixon** [comment]
@alanhoff @bsiddiqui updated. See if that works for you fellas

**Comment by alanhoff** [comment]
@jamesdixon my bad, fixing it rn
