### ISSUE TITLE
method compare

### ISSUE THREAD

**Issue by igoreliasm** [bsiddiqui/bookshelf-bcrypt#9]
There is documentation about the method compare?
Because its don't returned the response when I compare like that:

```
user.forge({ email: req.body.email })
  .fetch({ require: true })
  //.then((user) => user.compare(req.body.pass))
  //.then((isValid) => res({login: isValid}))
  .then(function(user){
    user.compare(req.body.pass)
  })
  .then(function(isValid){
    res.send({ login: isValid }), function(err){
      res.send(error);
    }
  });
```

reponse:

```
{}
```

**Comment by bsiddiqui** [comment]
@igoreliasm is the result your fetch properly returning a bookshelf model?

**Comment by igoreliasm** [comment]
@bsiddiqui 
I am creating a user normally, for example:

```
"pass": "$2a$12$/55BLOhUxs0waZki3wKYROcqe01tq7VusLw5eE4AXmZ61sHFXS6kq", 
```

```
module.exports = db.Model.extend({
  tableName: 'ew_user',
  hasTimestamps: true,
  bcrypt: {
    field: 'pass'
  }
});

```

If I use arrow function like that:

```
.then((user) => user.compare(req.body.pass))
.then((isValid) => res({login: isValid}))
```

I received:

```
Unhandled rejection Error: data and hash arguments required

```

I think is necessary insert the password already encrypted.

**Comment by bsiddiqui** [comment]
@igoreliasm how are you creating a user? you do not need to encrypt when you insert

**Comment by igoreliasm** [comment]
Why?
just:

```
user.forge(req.body)
  .save()
  .then(function(user){
    res.send(user), function(err){
      res.send(err);
    }
  });
```

I need save password in format bcrypt on database;

**Comment by bsiddiqui** [comment]
@igoreliasm are you receiving a already encrypted password from the user? `bookshelf-bcrypt` will handle encrypting and you can see the tests to see how it saves and compares. From the examples you're sending it looks like you're doing it right. I would do some debugging to make sure the password is encrypted when you save.

**Comment by igoreliasm** [comment]
@bsiddiqui  nope, the user have a password not encrypted, after I insert the user the password is encrypted, I just can't compare the login

**Comment by igoreliasm** [comment]
@bsiddiqui no problem, for me its ok, but don't work

**Comment by igoreliasm** [comment]
@bsiddiqui It appears not work well on sqlite, ou can to be something with sqlite here, because I changed the knexfile to mysql and worked! :dancer:

**Comment by bsiddiqui** [comment]
@igoreliasm glad you found a solution. I'll close the issue for now. Feel free to make a PR if you figure out how to make it work for sqlite.
